/**
 * Factory Standards - License Injector
 * 
 * Bu modül, fabrikadan çıkan HER otomasyona lisans koruması ekler.
 * Standalone projeler bu dosyayı otomatik olarak içerir.
 */

const FACTORY_VERSION = '3.1';
const LICENSE_SERVER = 'https://omniflow-automation-bot.netlify.app/.netlify/functions/validate-license';

/**
 * Generate standard license service code for any automation
 */
function generateLicenseServiceCode(productId: string): string {
    return `/**
 * License Validation Service
 * Auto-generated by OmniFlow Factory v${FACTORY_VERSION}
 * Product: ${productId}
 */

const crypto = require('crypto');

const LICENSE_SERVER = '${LICENSE_SERVER}';
const PRODUCT_ID = '${productId}';

let licenseCache = { key: null, expiresAt: 0, valid: false };

async function validateLicense(licenseKey) {
    if (!licenseKey) {
        return { valid: false, message: 'LICENSE_KEY required in .env' };
    }

    const machineId = generateMachineFingerprint();

    try {
        const response = await fetch(LICENSE_SERVER, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ licenseKey, productId: PRODUCT_ID, machineId })
        });

        if (response.ok) {
            const result = await response.json();
            if (result.valid) {
                licenseCache = { key: licenseKey, expiresAt: Date.now() + 7 * 24 * 60 * 60 * 1000, valid: true };
            }
            return result;
        }
    } catch (e) {
        if (licenseCache.valid && licenseCache.expiresAt > Date.now()) {
            return { valid: true, message: 'Offline mode (cached)' };
        }
    }

    return { valid: false, message: 'License validation failed' };
}

function generateMachineFingerprint() {
    const os = require('os');
    const data = [os.hostname(), os.platform(), os.arch(), os.cpus()[0]?.model || '', os.totalmem()].join('|');
    return crypto.createHash('sha256').update(data).digest('hex').substring(0, 32);
}

function requireLicense() {
    return async (req, res, next) => {
        const licenseKey = req.headers['x-license-key'] || process.env.LICENSE_KEY;
        const result = await validateLicense(licenseKey);
        if (!result.valid) {
            return res.status(403).json({ error: 'License Required', message: result.message, purchaseUrl: 'https://omniflow.com/products/${productId}' });
        }
        req.license = result;
        next();
    };
}

module.exports = { validateLicense, requireLicense, PRODUCT_ID };
`;
}

/**
 * Generate protected Express server template
 */
function generateProtectedServerTemplate(productId: string, productName: string): string {
    return `/**
 * ${productName} - Standalone Server
 * Auto-generated by OmniFlow Factory v${FACTORY_VERSION}
 * 
 * LICENSE PROTECTED - Requires valid license to run
 */

require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { requireLicense, PRODUCT_ID } = require('./services/license');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Health check (no license)
app.get('/', (req, res) => {
    res.json({
        product: '${productName}',
        version: '1.0.0',
        licensed: !!process.env.LICENSE_KEY,
        generator: 'OmniFlow Factory v${FACTORY_VERSION}'
    });
});

// All API routes are LICENSE PROTECTED
// Add your routes here with requireLicense() middleware:
// app.use('/api/your-route', requireLicense(), yourRouter);

// Error handler
app.use((err, req, res, next) => {
    console.error(err);
    res.status(500).json({ error: err.message });
});

app.listen(PORT, () => {
    console.log(\`🚀 \${process.env.LICENSE_KEY ? '🔓 Licensed' : '🔒 Unlicensed'} server running on port \${PORT}\`);
});

module.exports = app;
`;
}

/**
 * Generate package.json for standalone automation
 */
function generatePackageJson(productId: string, productName: string): object {
    return {
        name: productId,
        version: '1.0.0',
        description: `${productName} - Standalone automation. No n8n required!`,
        main: 'server/index.js',
        scripts: {
            start: 'node server/index.js',
            dev: 'nodemon server/index.js'
        },
        dependencies: {
            express: '^4.18.2',
            cors: '^2.8.5',
            dotenv: '^16.3.1'
        },
        devDependencies: {
            nodemon: '^3.0.2'
        },
        engines: {
            node: '>=18.0.0'
        },
        license: 'SEE LICENSE IN LICENSE.md',
        _generator: `OmniFlow Factory v${FACTORY_VERSION}`,
        _protected: true
    };
}

/**
 * Generate env.example template
 */
function generateEnvExample(productId: string, requiredApis: string[]): string {
    const apiSections: Record<string, string> = {
        twilio: `# === TWILIO ===
TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxx
TWILIO_AUTH_TOKEN=xxxxxxxxxxxx
TWILIO_PHONE_NUMBER=+1xxxxxxxxxx`,
        stripe: `# === STRIPE ===
STRIPE_SECRET_KEY=sk_test_xxxx
STRIPE_WEBHOOK_SECRET=whsec_xxxx`,
        zoom: `# === ZOOM ===
ZOOM_API_KEY=xxxxxxxxxxxx
ZOOM_API_SECRET=xxxxxxxxxxxx`,
        supabase: `# === SUPABASE ===
SUPABASE_URL=https://xxxx.supabase.co
SUPABASE_ANON_KEY=xxxxxxxxxxxx`,
        openai: `# === OPENAI ===
OPENAI_API_KEY=sk-xxxxxxxxxxxx`,
        huggingface: `# === HUGGING FACE ===
HUGGINGFACE_TOKEN=hf_xxxxxxxxxxxx`,
        smtp: `# === EMAIL (SMTP) ===
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your-email@gmail.com
SMTP_PASS=app-password`
    };

    let output = `# ${productId.toUpperCase()} - Environment Variables
# Generated by OmniFlow Factory v${FACTORY_VERSION}

# === LICENSE (REQUIRED) ===
LICENSE_KEY=OMNI-XXXX-XXXX-XXXX-XXXX

# === SERVER ===
PORT=3000
NODE_ENV=production
`;

    for (const api of requiredApis) {
        if (apiSections[api.toLowerCase()]) {
            output += `\n${apiSections[api.toLowerCase()]}\n`;
        }
    }

    return output;
}

/**
 * Factory Standards Export
 */
export const factoryStandards = {
    version: FACTORY_VERSION,
    licenseServer: LICENSE_SERVER,
    generateLicenseServiceCode,
    generateProtectedServerTemplate,
    generatePackageJson,
    generateEnvExample,

    // Core principles
    principles: {
        NO_N8N: 'All automations are standalone Node.js, no n8n required',
        LICENSE_PROTECTED: 'All automations require valid license to run',
        REAL_CODE: 'No demos, only production-ready code',
        MINIMAL_COST: 'Customer only pays for their own API usage'
    }
};

export default factoryStandards;
