
import { WorkflowNode, NodeType, SystemBlueprint } from '../types';

// ============================================
// INTEGRATION SERVICE - Gerçek API Bağlantıları
// ============================================

export interface IntegrationConfig {
  type: 'whatsapp' | 'telegram' | 'discord' | 'webhook' | 'email' | 'coingecko' | 'ayrshare' | 'mediatools' | 'alphavantage' | 'pexels' | 'googlecalendar' | 'hubspot' | 'groq' | 'shopify' | 'gumroad';
  name: string;
  credentials: Record<string, string>;
  isActive: boolean;
}

export interface WebhookPayload {
  event: string;
  data: any;
  timestamp: string;
  source: string;
}

// ============================================
// WHATSAPP INTEGRATION (Baileys-based)
// ============================================
export const whatsappConfig = {
  generateConnectionCode: (): string => {
    // QR code için bağlantı kodu üret
    return `WA_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  },

  createMessageHandler: (blueprint: SystemBlueprint) => {
    return `
// WhatsApp Bot - ${blueprint.name}
// Auto-generated by OmniFlow Factory

const { default: makeWASocket, useMultiFileAuthState, DisconnectReason } = require('@whiskeysockets/baileys');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function startBot() {
  const { state, saveCreds } = await useMultiFileAuthState('auth_info');
  
  const sock = makeWASocket({
    auth: state,
    printQRInTerminal: true
  });

  sock.ev.on('creds.update', saveCreds);

  sock.ev.on('messages.upsert', async ({ messages }) => {
    const msg = messages[0];
    if (!msg.message || msg.key.fromMe) return;

    const text = msg.message.conversation || msg.message.extendedTextMessage?.text || '';
    const from = msg.key.remoteJid;

    console.log('📩 Mesaj:', text);

    // AI ile cevap üret
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
    const prompt = \`Sen bir müşteri asistanısın. Sistem: ${blueprint.baseKnowledge}
    
Müşteri mesajı: \${text}

Kısa ve yardımcı bir cevap ver.\`;

    try {
      const result = await model.generateContent(prompt);
      const response = result.response.text();
      
      await sock.sendMessage(from, { text: response });
      console.log('✅ Cevap gönderildi');
    } catch (err) {
      console.error('❌ Hata:', err);
      await sock.sendMessage(from, { text: 'Üzgünüm, bir hata oluştu. Lütfen tekrar deneyin.' });
    }
  });
}

startBot();
`;
  }
};

// ============================================
// TELEGRAM INTEGRATION
// ============================================
export const telegramConfig = {
  createBotCode: (blueprint: SystemBlueprint, botToken: string) => {
    return `
// Telegram Bot - ${blueprint.name}
// Auto-generated by OmniFlow Factory

const TelegramBot = require('node-telegram-bot-api');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const bot = new TelegramBot('${botToken || 'YOUR_BOT_TOKEN'}', { polling: true });
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

bot.on('message', async (msg) => {
  const chatId = msg.chat.id;
  const text = msg.text;

  if (text === '/start') {
    return bot.sendMessage(chatId, '🤖 Merhaba! Ben ${blueprint.name} asistanıyım. Size nasıl yardımcı olabilirim?');
  }

  const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
  const prompt = \`Sen bir asistansın. Sistem bilgisi: ${blueprint.baseKnowledge}
  
Kullanıcı: \${text}

Yardımcı ol.\`;

  try {
    const result = await model.generateContent(prompt);
    const response = result.response.text();
    bot.sendMessage(chatId, response);
  } catch (err) {
    bot.sendMessage(chatId, '❌ Bir hata oluştu.');
  }
});

console.log('🤖 Telegram bot çalışıyor...');
`;
  }
};

// ============================================
// DISCORD INTEGRATION
// ============================================
export const discordConfig = {
  createBotCode: (blueprint: SystemBlueprint, botToken: string) => {
    return `
// Discord Bot - ${blueprint.name}
// Auto-generated by OmniFlow Factory

const { Client, GatewayIntentBits } = require('discord.js');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent
  ]
});

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

client.on('ready', () => {
  console.log('🤖 Discord bot hazır: ' + client.user.tag);
});

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;
  if (!message.content.startsWith('!ask')) return;

  const query = message.content.replace('!ask', '').trim();
  
  const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
  const prompt = \`Sistem: ${blueprint.baseKnowledge}
Soru: \${query}\`;

  try {
    const result = await model.generateContent(prompt);
    message.reply(result.response.text());
  } catch (err) {
    message.reply('❌ Hata oluştu.');
  }
});

client.login('${botToken || 'YOUR_BOT_TOKEN'}');
`;
  }
};

// ============================================
// GENERIC WEBHOOK
// ============================================
export const webhookConfig = {
  sendWebhook: async (url: string, payload: WebhookPayload): Promise<boolean> => {
    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      return response.ok;
    } catch (e) {
      console.error('Webhook error:', e);
      return false;
    }
  },

  createExpressServer: (blueprint: SystemBlueprint) => {
    return `
// Webhook Server - ${blueprint.name}
// Auto-generated by OmniFlow Factory

const express = require('express');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const app = express();
app.use(express.json());

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Webhook endpoint
app.post('/webhook', async (req, res) => {
  console.log('📩 Webhook alındı:', req.body);

  const { event, data } = req.body;

  // AI ile işle
  const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
  const prompt = \`Sistem: ${blueprint.baseKnowledge}
Event: \${event}
Data: \${JSON.stringify(data)}

Bu veriyi işle ve uygun aksiyonu belirle.\`;

  try {
    const result = await model.generateContent(prompt);
    const response = result.response.text();
    
    res.json({ success: true, action: response });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', system: '${blueprint.name}' });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log('🚀 Webhook server çalışıyor: http://localhost:' + PORT);
});
`;
  }
};

// ============================================
// INTEGRATION MANAGER
// ============================================
export class IntegrationManager {
  private integrations: IntegrationConfig[] = [];

  constructor() {
    this.loadFromStorage();
  }

  private loadFromStorage() {
    const saved = localStorage.getItem('omni_integrations');
    if (saved) {
      this.integrations = JSON.parse(saved);
    }
  }

  private saveToStorage() {
    localStorage.setItem('omni_integrations', JSON.stringify(this.integrations));
  }

  addIntegration(config: IntegrationConfig) {
    this.integrations.push(config);
    this.saveToStorage();
  }

  removeIntegration(name: string) {
    this.integrations = this.integrations.filter(i => i.name !== name);
    this.saveToStorage();
  }

  getIntegrations(): IntegrationConfig[] {
    return this.integrations;
  }

  getActiveIntegrations(): IntegrationConfig[] {
    return this.integrations.filter(i => i.isActive);
  }
}

export const integrationManager = new IntegrationManager();
