/**
 * Standalone Runner Template
 * This is the template for the index.js file generated by the factory.
 */

export const STANDALONE_RUNNER_CODE = (blueprint: any) => `
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";
import fs from "fs";

dotenv.config();

const API_KEY = process.env.GEMINI_API_KEY;
if (!API_KEY) {
  console.error("❌ HATA: .env dosyasında GEMINI_API_KEY bulunamadı");
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(API_KEY);
const BLUEPRINT = ${JSON.stringify(blueprint, null, 2)};

async function runAutomationStep(node) {
  console.log(\`🚀 Çalıştırılıyor: [\${node.type.toUpperCase()}] \${node.title}\`);
  
  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
  
  const prompt = \`
    Sen bir Yapay Zeka Otomasyon Ajanısın. 
    Görev: \${node.task}
    Rol: \${node.role}
    Bağlam: \${BLUEPRINT.masterGoal}
    Bilgi Temeli: \${BLUEPRINT.baseKnowledge}
    
    Lütfen sonucu istenen formatta (metin veya yapılandırılmış veri) döndür.
  \`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    console.log("✅ Başarılı!");
    return text;
  } catch (error) {
    console.error("❌ Adım Başarısız Oldu:", error.message);
    return null;
  }
}

async function main() {
  console.log("-----------------------------------------");
  console.log(\`📦 OMNIFLOW BAĞIMSIZ YÜRÜTÜCÜ: \${BLUEPRINT.name}\`);
  console.log(\`🎯 HEDEF: \${BLUEPRINT.masterGoal}\`);
  console.log("-----------------------------------------");

  const results = {};

  for (const node of BLUEPRINT.nodes) {
    const output = await runAutomationStep(node);
    results[node.id] = output;
    
    // Ara sonucu kaydet
    fs.writeFileSync(\`sonuc_\${node.id}.txt\`, output || "BAŞARISIZ");
  }

  console.log("\\n✨ TÜM ADIMLAR TAMAMLANDI.");
  console.log("Sonuçlar için üretilen .txt dosyalarını kontrol edin.");
}

main().catch(console.error);
`;

export const STANDALONE_PACKAGE_JSON = (projectName: string) => JSON.stringify({
  "name": projectName.toLowerCase().replace(/\s+/g, "-"),
  "version": "1.0.0",
  "description": "OmniFlow Bağımsız Otomasyon Yürütücüsü",
  "main": "index.js",
  "type": "module",
  "dependencies": {
    "@google/generative-ai": "^0.21.0",
    "dotenv": "^16.4.5"
  }
}, null, 2);

export const STANDALONE_ENV_EXAMPLE = `
# OmniFlow Bağımsız Yürütücü Yapılandırması
# API Anahtarınızı buradan alabilirsiniz: https://aistudio.google.com/app/apikey

GEMINI_API_KEY=buraya_api_anahtarinizi_yazin
`;

export const STANDALONE_README = (projectName: string) => `
# 📦 ${projectName} - Bağımsız Yürütücü (Standalone)

Bu paket **OmniFlow Profit Factory** tarafından otomatik olarak oluşturulmuş bağımsız bir otomasyon paketidir.

## 🚀 Hızlı Başlangıç

1. **Bağımlılıkları Yükleyin**:
   \`\`\`bash
   npm install
   \`\`\`

2. **Yapılandırma**:
   - \`.env.example\` dosyasını \`.env\` olarak kopyalayın.
   - \`.env\` dosyasının içine \`GEMINI_API_KEY\` anahtarınızı ekleyin.

3. **Otomasyonu Çalıştırın**:
   - Windows için: \`baslat.bat\` dosyasına çift tıklayın.
   - Terminalden: \`node index.js\`

## 📂 Dosya Yapısı

- \`index.js\`: Ana yürütücü motor.
- \`blueprint.json\`: Otomasyon mantığı ve prompt yapılandırması.
- \`.env\`: Size özel API anahtarları.
- \`baslat.bat\`: Hızlı başlatma betiği.
- \`requirements.txt\`: Bağımlılık listesi (Görsel referans).
- \`sonuc_*.txt\`: Çalıştırma sonrası üretilen çıktı dosyaları.

---
*OmniFlow Factory v3.2 tarafından üretilmiştir*
`;

export const STANDALONE_BAT_SCRIPT = `
@echo off
title OmniFlow Bağımsız Yürütücü
echo 🚀 Otomasyon başlatılıyor...
node index.js
pause
`;

export const STANDALONE_REQUIREMENTS = `
# OmniFlow Bağımsız Paket Bağımlılıkları
# Bu dosyayı 'npm install' komutu ile yükleyebilirsiniz.

@google/generative-ai
dotenv
fs
`;

export const STANDALONE_PUBLISH_GUIDE = (projectName: string) => `
# 🛠️ ${projectName} - Nasıl Yayınlanır?

Bu otomasyonu bir ürün olarak yayınlamak veya müşterilerinize sunmak için aşağıdaki adımları izleyebilirsiniz:

### 1. Dosya Temizliği
- \`.env\` dosyasını asla paylaşmayın. Sadece \`.env.example\` kalsın.
- Varsa \`sonuc_*.txt\` dosyalarını silin.

### 2. Paketleme (Zip)
- Tüm dosyaları bir .zip arşivi haline getirin.
- İsimlendirme formatı: \`${projectName.toLowerCase().replace(/\s+/g, "_")}_V1.0.zip\`

---
*OmniFlow Factory Tarafından Hazırlanmıştır*
`;
